<a href="https://colab.research.google.com/github/TangenAiden/MIS433/blob/main/Copy_of_assignment_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In this assignment, you will be working with this dataset of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [148]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [149]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [150]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/MyDrive/imdb_top_1000 (1).csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [151]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [152]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [153]:
# Display Series_Title, Released_Year, and IMDB_Rating of the top 10 movies.
imdb[['Series_Title','Released_Year','IMDB_Rating']].head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [154]:
# Display movies ranked 11-20.
# Show their Series_Title, Released_Year, and IMDB_Rating.
imdb[['Series_Title','Released_Year','IMDB_Rating']].iloc[10:20]

,Series_Title,Released_Year,IMDB_Rating
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
11,Forrest Gump,1994,8.8
12,"Il buono, il brutto, il cattivo",1966,8.8
13,The Lord of the Rings: The Two Towers,2002,8.7
14,The Matrix,1999,8.7
15,Goodfellas,1990,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
18,Hamilton,2020,8.6
19,Gisaengchung,2019,8.6

It says 19 but that is the 20th ranked movie.

In [155]:
# Select all movies directed by Quentin Tarantino.
# Show their Series_Title, Released_Year, IMDB_Rating, and Gross.
imdb[imdb.Director == "Quentin Tarantino"][['Series_Title','Released_Year','IMDB_Rating','Gross']].reset_index()

,index,Series_Title,Released_Year,IMDB_Rating,Gross
0,6,Pulp Fiction,1994,8.9,"107,928,762"
1,62,Django Unchained,2012,8.4,"162,805,434"
2,93,Inglourious Basterds,2009,8.3,"120,540,719"
3,103,Reservoir Dogs,1992,8.3,"2,832,029"
4,241,Kill Bill: Vol. 1,2003,8.1,"70,099,045"
5,369,Kill Bill: Vol. 2,2004,8.0,"66,208,183"
6,584,The Hateful Eight,2015,7.8,"54,117,416"
7,879,Once Upon a Time... in Hollywood,2019,7.6,"142,502,728"

In [156]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and IMDB_Rating.
imdb.loc[(imdb.Certificate == "R") & (imdb.IMDB_Rating >= 8.5),['Series_Title','Released_Year','Certificate','IMDB_Rating']]

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [157]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb.Released_Year.nunique()

100

In [158]:
# Count the number of movies in each "Released_Year".
# Hint: value_counts()
imdb.Released_Year.value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [159]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's year is not.
# Find this movie.
imdb.Released_Year.unique()
imdb.loc[(imdb.Released_Year == 'PG')][['Series_Title','Released_Year']]

    Series_Title Released_Year
966    Apollo 13            PG

In [160]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_index, column_name] = new_value
imdb.loc[966, "Released_Year"] = "1995"
imdb.loc[966, "Certificate"] = "PG"
imdb[["Released_Year","Certificate"]].loc[966]

Released_Year    1995
Certificate        PG
Name: 966, dtype: object

In [161]:
# Change the data type of "Released_Year" to int
imdb['Released_Year'] = imdb['Released_Year'].astype(int)

In [162]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and IMDB_Rating.
imdb.loc[(imdb.Released_Year >=2010) & (imdb.IMDB_Rating >=8.5),['Series_Title','Released_Year','Certificate','IMDB_Rating']]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [163]:
# Select all movies whose genres contain 'Animation'
imdb.loc[imdb.Genre.str.contains('Animation'), ['Series_Title','Released_Year','Certificate','IMDB_Rating']]

                          Series_Title  Released_Year Certificate  IMDB_Rating
23       Sen to Chihiro no kamikakushi           2001           U          8.6
43                       The Lion King           1994           U          8.5
46                      Hotaru no haka           1988           U          8.5
56                      Kimi no na wa.           2016           U          8.4
58   Spider-Man: Into the Spider-Verse           2018           U          8.4
..                                 ...            ...         ...          ...
956                              Mulan           1998           U          7.6
971                  Omohide poro poro           1991           U          7.6
976                 The Little Mermaid           1989           U          7.6
986                     Watership Down           1978           U          7.6
992                    The Jungle Book           1967           U          7.6

[82 rows x 4 columns]

In [164]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title','Released_Year','Star1','Star2','Star3','Star4']]
stars.head(10)

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
5,The Lord of the Rings: The Return of the King,2003,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom
6,Pulp Fiction,1994,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis
7,Schindler's List,1993,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall
8,Inception,2010,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe
9,Fight Club,1999,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier

In [165]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title','Released_Year','Genre']]
genres.head(10)

,Series_Title,Released_Year,Genre
0,The Shawshank Redemption,1994,Drama
1,The Godfather,1972,"Crime, Drama"
2,The Dark Knight,2008,"Action, Crime, Drama"
3,The Godfather: Part II,1974,"Crime, Drama"
4,12 Angry Men,1957,"Crime, Drama"
5,The Lord of the Rings: The Return of the King,2003,"Action, Adventure, Drama"
6,Pulp Fiction,1994,"Crime, Drama"
7,Schindler's List,1993,"Biography, Drama, History"
8,Inception,2010,"Action, Adventure, Sci-Fi"
9,Fight Club,1999,Drama

In [166]:
# Sorting:
# Sort the genres dataframe in ascending order of "Released_Year"
genres.sort_values('Released_Year',ascending=True)

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [167]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and Gross.
# Sort them in descending order of "Gross"
imdb.loc[(imdb.Released_Year >= 2010) & (imdb.IMDB_Rating >= 8.5),['Series_Title','Released_Year','Certificate','Gross']].sort_values('Gross',ascending=False)

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [168]:
# Does the sorting result look right to you? What's the problem?

The sorting result does not look right due to the fact that the top of the results grossed less than the results before it. It should be below interstellar if the list was correct

In [184]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe
imdb['Gross'] = imdb['Gross'].str.replace(',', '')
imdb['Gross'] = imdb['Gross'].astype(float)

In [185]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and Gross.
# Sort them in descending order of "Gross"
imdb.loc[(imdb.Released_Year >= 2010) & (imdb.IMDB_Rating >= 8.5),['Series_Title','Released_Year','Certificate','Gross']].sort_values('Gross',ascending=False)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [187]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
imdb['Runtime_min'] = imdb['Runtime'].str[:-4].astype(int)

In [188]:
# Add a new column "Age_Years" by the expression: Current year - Released_Year
imdb['Age_Years'] = 2026 - imdb['Released_Year']

In [189]:
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Runtime_min,Age_Years
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,142,32
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,175,54
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,152,18
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,202,52
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,96,69

In [190]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10

In [191]:
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Runtime_min,Age_Years,Decade
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,142,32,1990
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,175,54,1970
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,152,18,2000
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,202,52,1970
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,96,69,1950

## Part 2: Data Summarization

In [193]:
# Total "Gross" of all top 1000 movies
print(imdb['Gross'].sum())

56536877976.0

In [195]:
# Average "No_of_Votes" of all movies
print(imdb['No_of_Votes'].mean())

273692.911

In [198]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
imdb['Decade'].value_counts()

Decade
2010    242
2000    237
1990    151
1980     89
1970     76
1960     73
1950     56
1940     35
1930     24
1920     11
2020      6
Name: count, dtype: int64

In [199]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
imdb['Director'].value_counts().head(10)

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [204]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Rank them in descending order of total gross
# Show the top 10 directors with the highest total gross
(
    imdb.groupby('Director').agg(
        NumMovie=('Series_Title','count'),
        AVGIMDBR=('IMDB_Rating','mean'),
        TG=('Gross','sum')
    ).sort_values('TG',ascending=False).head(10)
)

                   NumMovie  AVGIMDBR            TG
Director
Steven Spielberg         13  8.030769  2.478133e+09
Anthony Russo             4  8.075000  2.205039e+09
Christopher Nolan         8  8.462500  1.937454e+09
James Cameron             5  8.080000  1.748237e+09
Peter Jackson             5  8.400000  1.597312e+09
J.J. Abrams               3  7.833333  1.423171e+09
Brad Bird                 4  7.900000  1.099628e+09
Robert Zemeckis           5  8.120000  1.049446e+09
David Yates               3  7.800000  9.789537e+08
Pete Docter               4  8.125000  9.393821e+08

In [212]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count
(
    imdb.groupby(['Director','Decade']).agg(NumMovie=('Series_Title','count'),AVGIMDBR=('IMDB_Rating','mean')).sort_values('NumMovie',ascending=False).head(10)
)

                             NumMovie  AVGIMDBR
Director             Decade
Billy Wilder         1950           6  8.133333
Alfred Hitchcock     1940           5  7.880000
                     1950           5  8.220000
Denis Villeneuve     2010           5  7.980000
Akira Kurosawa       1950           5  8.260000
Clint Eastwood       2000           5  7.940000
Steven Spielberg     1980           5  7.980000
Rob Reiner           1980           4  7.900000
Christopher Nolan    2000           4  8.525000
Krzysztof Kieslowski 1990           4  7.850000

In [215]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking
top3 = imdb.loc[imdb.Released_Year >= 2010].sort_values(['Released_Year', 'IMDB_Rating'], ascending=[False, False])
top3['Ranking'] = top3.groupby('Released_Year').cumcount()+1
top3.loc[top3.Ranking <=3,['Released_Year', 'Ranking', 'Series_Title', 'IMDB_Rating']]

     Released_Year  Ranking                       Series_Title  IMDB_Rating
18            2020        1                           Hamilton          8.6
20            2020        2                    Soorarai Pottru          8.6
205           2020        3                               Soul          8.1
19            2019        1                       Gisaengchung          8.6
33            2019        2                              Joker          8.5
59            2019        3                  Avengers: Endgame          8.4
53            2018        1                         Capharnaüm          8.4
58            2018        2  Spider-Man: Into the Spider-Verse          8.4
60            2018        3             Avengers: Infinity War          8.4
54            2017        1          Ayla: The Daughter of War          8.4
55            2017        2                       Vikram Vedha          8.4
61            2017        3                               Coco          8.4
56            2016        1                     Kimi no na wa.          8.4
57            2016        2                             Dangal          8.4
196           2016        3                               Pink          8.1
133           2015        1                             Talvar          8.2
136           2015        2                           Drishyam          8.2
203           2015        3                               Room          8.1
21            2014        1                       Interstellar          8.6
34            2014        2                           Whiplash          8.5
200           2014        3                              Mommy          8.1
87            2013        1                           Drishyam          8.3
137           2013        2                              Queen          8.2
138           2013        3                        Mandariinid          8.2
62            2012        1                   Django Unchained          8.4
63            2012        2              The Dark Knight Rises          8.4
88            2012        3                             Jagten          8.3
35            2011        1                   The Intouchables          8.5
89            2011        2            Jodaeiye Nader az Simin          8.3
144           2011        3                            Warrior          8.2
8             2010        1                          Inception          8.8
90            2010        2                          Incendies          8.3
141           2010        3                              Udaan          8.2

In [228]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.
director_decade = imdb.groupby('Director')['Decade'].nunique()
fived = director_decade[director_decade>=5].index
imdb.loc[imdb.Director.isin(fived), ['Director', 'Decade']].value_counts().sort_index().reset_index(name='Num_Movies')

            Director  Decade  Num_Movies
0     Hayao Miyazaki    1970           1
1     Hayao Miyazaki    1980           4
2     Hayao Miyazaki    1990           2
3     Hayao Miyazaki    2000           3
4     Hayao Miyazaki    2010           1
5    Martin Scorsese    1970           1
6    Martin Scorsese    1980           3
7    Martin Scorsese    1990           2
8    Martin Scorsese    2000           1
9    Martin Scorsese    2010           3
10  Steven Spielberg    1970           2
11  Steven Spielberg    1980           5
12  Steven Spielberg    1990           3
13  Steven Spielberg    2000           2
14  Steven Spielberg    2010           1

In [233]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1: What is the highest grossing steven spielberg movie on this list?
imdb.loc[imdb.Director =="Steven Spielberg",['Series_Title', 'Released_Year', 'Gross']].sort_values('Gross',ascending=False).head(1)

                   Series_Title  Released_Year        Gross
688  E.T. the Extra-Terrestrial           1982  435110554.0

In [237]:
# Question 2: What is the combined gross from lord of the rings?

LordoftheRingsGross = imdb.loc[imdb.Series_Title.str.contains('Lord of the Rings'), ['Series_Title', 'Released_Year', 'Gross']]
print(LordoftheRingsGross['Gross'].sum())

1035942020.0